# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flex_attention

# Data training arguments
dataset_name: SynthLabsAI/Big-Math-RL-Verified
dataset_prompt_column: problem
dataset_answer_column: answer
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the boxed answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n\\boxed{...}\n</answer>"

# GRPO trainer config
bf16: true
beta: 0.04
use_vllm: true
do_eval: false
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-Instruct-GRPO-BigMath
hub_strategy: every_save
hub_private_repo: true
learning_rate: 2.0e-05
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 16
num_train_epochs: 4
output_dir: runs/Qwen2.5-1.5B-Instruct-GRPO-BigMath
overwrite_output_dir: false
per_device_eval_batch_size: 16
per_device_train_batch_size: 32
push_to_hub: true
report_to:
- wandb
reward_funcs:
- verl_math_reward # accuracy, accuracy_with_timeout, verl_math_reward
- format
- tag_count
reward_weights:
- 0.8
- 0.1
- 0.1
scale_rewards: false # group: standard, none: Dr GRPO, batch: PPO Lite / DAPO
epsilon_high: 0.28 # null: standard, > 0.2 (e.g. 0.28): DAPO
loss_type: "dr_grpo" # grpo, dr_grpo, dapo, bnpo
mask_truncated_completions: true # recommended in DAPO
sync_ref_model: false # true: synchronize reference with active model every k steps as in TR-DPO
top_entropy_quantile: 0.8
use_liger_loss: false
save_strategy: epoch
save_total_limit: 4
seed: 42
warmup_ratio: 0.1
