# Model arguments
model_name_or_path: FreedomIntelligence/openPangu-Embedded-1B
trust_remote_code: true
local_files_only: true
model_revision: main
torch_dtype: bfloat16
attn_implementation: flex_attention #flash_attention_2

# Data training arguments
chat_template: "{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '[unused9]系统：[unused10]' }}{% endif %}{% if message['role'] == 'system' %}{{ '[unused9]系统：' + message['content'] + '[unused10]' }}{% endif %}{% if message['role'] == 'assistant' %}{{'[unused9]助手：' + message['content'] + '[unused10]'}}{% endif %}{% if message['role'] == 'tool' %}{{'[unused9]工具：' + message['content'] + '[unused10]'}}{% endif %}{% if message['role'] == 'function' %}{{'[unused9]方法：' + message['content'] + '[unused10]'}}{% endif %}{% if message['role'] == 'user' %}{{'[unused9]用户：' + message['content'] + '[unused10]'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '[unused9]助手：' }}{% endif %}"
dataset_name: nlile/hendrycks-MATH-benchmark
dataset_prompt_column: problem
dataset_answer_column: answer
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the boxed answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n\\boxed{...}\n</answer>"

# GRPO trainer config
bf16: true
beta: 0.04
use_vllm: true
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: openPangu-Embedded-1B-GRPO-Math1k
hub_strategy: every_save
hub_private_repo: true
learning_rate: 2.0e-05
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 16
num_train_epochs: 4
output_dir: runs/openPangu-Embedded-1B-GRPO-Math1k
overwrite_output_dir: false
per_device_eval_batch_size: 16
per_device_train_batch_size: 64
push_to_hub: true
report_to:
- wandb
reward_funcs:
- verl_math_reward # accuracy, accuracy_with_timeout, verl_math_reward
- format
- tag_count
reward_weights:
- 0.8
- 0.1
- 0.1
scale_rewards: false # group: standard, none: Dr GRPO, batch: PPO Lite / DAPO
epsilon_high: 0.28 # null: standard, > 0.2 (e.g. 0.28): DAPO
loss_type: "dr_grpo" # grpo, dr_grpo, dapo, bnpo
mask_truncated_completions: true # recommended in DAPO
sync_ref_model: false # true: synchronize reference with active model every k steps as in TR-DPO
top_entropy_quantile: 0.8
use_liger_loss: false
save_strategy: epoch
save_total_limit: 4
seed: 42
warmup_ratio: 0.1
