model_parameters:
  model_name: Qwen/Qwen2.5-1.5B-Instruct
  revision: main
  max_length: 32768
  dtype: bfloat16
  compile: true
  model_parallel: false
#  batch_size: 1
  trust_remote_code: true
  generation_parameters:
    #num_blocks: 4096
    #block_size: 64
    max_new_tokens: 32768
    temperature: 0.6
    top_p: 0.95